Fix failing tests The following errors are fixed FAILED tests/test_measurements.py::test_bigwig_measurement - TypeError: get_data() missing 1 required positional argument: ‘bins’ FAILED tests/test_measurements.py::test_bigbed_measurement - TypeError: get_data() missing 1 required positional argument: ‘bins’